### ISSUE TITLE
Doesnt work with non latin characters

### ISSUE THREAD

**Issue by kirillsulim** [kirillsulim/desman#12]
```txt
[sulim@sulim-skbkontur hercules-elk-adapter-requests]$ desman -e env/devlocal.yml -sbH push-logs.yml 
'latin-1' codec can't encode characters in position 140-144: Body ('Рюске') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
Traceback (most recent call last):
  File "/home/sulim/.local/bin/desman", line 11, in <module>
    sys.exit(main())
  File "/home/sulim/.local/lib/python3.6/site-packages/desman/desman.py", line 69, in main
    App().run(sys.argv)
  File "/home/sulim/.local/lib/python3.6/site-packages/desman/desman.py", line 39, in run
    response = self.run_request(request_data)
  File "/home/sulim/.local/lib/python3.6/site-packages/desman/desman.py", line 51, in run_request
    data=request_data.get('body'),
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1284, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib64/python3.6/http/client.py", line 161, in _encode
    (name.title(), data[err.start:err.end], name)) from None
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 140-144: Body ('Рюске') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

```

**Comment by kirillsulim** [comment]
Fixed in 1.0.2
